Add ability to define the amount of retries
GrahamCampbell/Guzzle-Factory pull request #6
Opened 2021-01-14 22:32 UTC by rickycheers

2021-01-14 22:44 UTC, rickycheers commented
Hi there!

I recently came across a use case where I needed to "turn off" or "disable" the automatic retries to prevent additional requests from flooding our web servers.

The way I worked around it was by manually creating the Guzzle client myself instead of using the this factory class. I figured something like this would be useful by someone else, so here it is. It not only allows you to disable the retries, but it even lets you increment them if needed.

Hope you find this useful, let me know if you have any comments.

2021-01-14 23:52 UTC, GrahamCampbell commented
Thanks for the PR. I don't follow the use case, however. If you don't need retries, then you don't need this package at all. Why can't you just do `$client = new Client()`?

2021-01-14 23:54 UTC, GrahamCampbell commented
Ah, I see, you want to easily turn it off temporarily.

2021-01-14 23:55 UTC, GrahamCampbell requested changes

2021-01-14 23:55 UTC, GrahamCampbell commented on src/GuzzleFactory.php
> +    public static function handler(int $backoff = null, array $codes = null, HandlerStack $stack = null, int $retries = null)
I'd prefer the parameter order to have stack at the end. We can just make this a major version bump.

2021-01-15 04:30 UTC, rickycheers commented
> Ah, I see, you want to easily turn it off temporarily.

Yeah, either that or simply being able to configure how many additional attempts to perform. I can imagine folks wanting to just make one additional attempt instead of 3

2021-01-24 20:05 UTC, merged

2021-01-24 20:05 UTC, GrahamCampbell commented
Thanks for working on this, and sorry for my slow merge! 🍻

2021-01-24 20:50 UTC, GrahamCampbell commented
v5.0.0 is out now. 🚀